DECLARE
    V_LOOPCOUNTER   INTEGER;
    V_SQLCMD        VARCHAR2(500);
    V_MSISDN        INTEGER;
    V_IMSI          INTEGER;

BEGIN
    -- GET MAX VALUES FOR UNIQUE COLUMNS
    SELECT
        MAX(to_number(MSISDN)) MAX_MSISDN,
        MAX(to_number(IMSI))   MAX_IMSI
    INTO
        V_MSISDN,
        V_IMSI
    FROM
        FWD_CMN.OMR_SUBSCRIBERS
          WHERE MSISDN != '9999999999' AND IMSI != '999999999999999';

    -- GENERATE DYN INSERT STATMENTS FOR OMR_SUBSCRIBERS

    FOR V_LOOPCOUNTER IN 1..100000 LOOP
        V_MSISDN := V_MSISDN + 1;
        V_IMSI := V_IMSI + 1;
        V_SQLCMD := 'INSERT INTO FWD_CMN.OMR_SUBSCRIBERS (IMSI, MSISDN, ENABLER_ZONE, MARKET, SUB_MARKET, LOCAL_MARKET, ACTIVE_DATE)
                            VALUES ('''||V_IMSI||''', '''||V_MSISDN||''', ''SER'', ''TNK'', ''NWS'', ''BOS'', SYSDATE)';
        --DBMS_OUTPUT.PUT_LINE(V_SQLCMD);
        EXECUTE IMMEDIATE V_SQLCMD;
    END LOOP;
    COMMIT;

EXCEPTION
  WHEN OTHERS THEN
                ROLLBACK;
END;